### ISSUE TITLE
Issue: Authentication Strategy and Third-Party Library

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#1]
### Background:
As we kick off the development of the Dairy Django Backend, it's crucial to establish a robust authentication strategy to secure our application. Since we are using Django REST framework, we have the flexibility to choose from various authentication methods and third-party libraries. This issue serves as a forum to discuss and decide on the most suitable approach for our project.

### Authentication Requirements:
To ensure a clear understanding, let's outline our authentication requirements:

1. **User Roles:**
   Define the roles that users will have in the system and the associated permissions.

2. **Security Levels:**
   Specify the required security levels for different parts of the application.

3. **Integration with Frontend:**
   Discuss how the authentication process will integrate with the frontend, especially considering the Angular frontend project.

### Proposed Solution:
I propose we use JSON Web Tokens (JWT) for authentication due to their stateless nature, scalability, and ease of integration with single-page applications. Additionally, the Django REST framework provides built-in support for JWT. Token authentication is a secure and efficient way to handle user sessions and requests.

### Discussion Points:

1. **Authentication Flow:**
   - Define the flow for user registration.
   - Discuss the login process and how tokens will be handled.
   - Consider password recovery mechanisms if needed.

2. **Third-Party Library:**
   - Explore Django REST framework's built-in authentication classes.
   - Discuss the pros and cons of using JWT.
   - Consider any alternative third-party libraries.

3. **Integration with Frontend:**
   - Address how the authentication process will integrate with our Angular frontend.
   - Discuss how the frontend will handle tokens.

4. **Security Considerations:**
   - Highlight any specific security considerations, such as token expiration and refresh mechanisms.

### Next Steps:

1. **Review and Feedback:**
   Please review the proposed solution and provide feedback.

2. **Alternative Approaches:**
   Feel free to suggest alternative authentication approaches and discuss their advantages and disadvantages.

3. **Decision Making:**
   Let's align on the chosen authentication strategy and any third-party libraries we'll be incorporating into the project.

### Additional Information:

- [Link to JWT documentation](https://jwt.io/introduction/)
- [Django REST framework authentication documentation](https://www.django-rest-framework.org/api-guide/authentication/)
- Any other relevant documentation or articles.

Let's collaborate on this issue to ensure we establish a secure and effective authentication mechanism, including token authentication, for our Dairy Django Backend.

**Comment by eadaradhiraj** [comment]
Are you intending to use djangorestframework-simplejwt first to get it up and running and then shift to a more robust token management system?

**Comment by peter-evance** [comment]
@eadaradhiraj Djoser and djangorestframework-simplejwt seems to be a great combo—RBAC (Maybe 5 user tier roles) is yet to be defined. 

May I get a gist of your implementation.

**Comment by eadaradhiraj** [comment]
> @eadaradhiraj Djoser and djangorestframework-simplejwt seems to be a great combo—RBAC (Maybe 5 user tier roles) is yet to be defined.
> 
> May I get a gist of your implementation.
I created the following three APIs
<img width="931" alt="image" src="https://github.com/AgriCodeHub/dairy-django-backend/assets/28575339/78faec96-0c70-482b-bf46-1d904f5f1e8c">

You register. This registration is only for normal user. Not a super user. A super user has to be created at the backend manualy via command line.

You log in with a password of your choosing and received a bearer token and refresh token.

Then you authorize by addding `Bearer <token>` when clicking the Authorize button on Swagger. Using curl you have to add the header Bearer.

You can logout by blacklisting the token in the db.
I also created the following two APIs:
resetting and changing passwords
For resetting the system gives out a uuid and token. Both these have to be filled out and a new password is to be given.

For changing password, the old password along with a new password are to be given.

All of these need test cases to ensure nothing goes wrong.

All of the above apis require a custom implementation of the User Manager and a custom User Model.

**Comment by peter-evance** [comment]
No djoser/third-party package right?

Seems too manual, in this case the tokens persist in the database right? — If so , do you have to actually create some cron job to delete the after some time.

**Comment by peter-evance** [comment]
> > No djoser/third-party package right?
> 
> No. Before I could use a third party package, the project had to change direction and move to session-based authentication because the UI team messed up.
> 
> > 
> > Seems too manual, in this case the tokens persist in the database right? — If so , do you have to actually create some cron job to delete the after some time.
> 
> As far as decommissioning of old tokens is concerned, there are probably better ways of implementation when using third party packages. We did use some rudimentary cronjob before shifting to session-based auth. What I did was a sort of a pilot implementation before being dropped entirely for reasons of resource unavailability.

Alright.

I'll consider djoser and simple JWT.
