### ISSUE TITLE
Issue: Enhance Lactation Model Integration with Pregnancy and Manual Entry

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#12]
#### Background:
In the ongoing development of the Dairy Django Backend, there's a need to enhance the Lactation model to seamlessly integrate with the Pregnancy model and allow for manual entry of lactation records, especially for bought cows.

#### Lactation Model Requirements:

- `start_date` (date): The start date of the lactation period.
- `end_date` (date or None): The end date of the lactation period, if available.
- `cow` (Cow): The cow associated with the lactation.
- `lactation_number` (int): The number assigned to the lactation.
- `pregnancy` (Pregnancy or None): The associated pregnancy record, if applicable.

#### Integration with Pregnancy Model:

- A successful calving event triggers the creation of a corresponding lactation record.
- For cows born on the farm, lactation records are automatically linked to the associated pregnancy.
- For bought cows, lactation records can be manually entered.

#### Methods:

- `days_in_lactation`: Calculates and returns the number of days in the lactation period.
- `lactation_stage`: Determines and returns the lactation stage based on the days in lactation.
- `end_date_`: Calculates and returns the expected end date of the lactation period.

#### Validation:

Validation checks are implemented before saving the lactation record to ensure data integrity.

### Discussion Points:

1. Define the attributes and methods in the Lactation model.
2. Discuss the integration with the Pregnancy model.
3. Address the process of manual entry for lactation records, especially for bought cows.
4. Any additional features or modifications needed for the Lactation model.

**Comment by steve2700** [comment]
im working on this now

**Comment by peter-evance** [comment]
> im working on this now

Sure, I have assigned you!
