### ISSUE TITLE
Implement Quarantine Record Model

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#19]
### Background
In the ongoing development of the Dairy Django Backend, the introduction of a QuarantineRecord model is crucial to effectively track and manage quarantine-related information for cows.

### QuarantineRecord Model Requirements
- **cow (Cow):** The cow associated with the quarantine record.
- **reason (Choice):** The reason for quarantine, selected from predefined choices.
- **start_date (Date):** The start date of the quarantine, automatically added.
- **end_date (Date):** The end date of the quarantine (optional).
- **notes (Text):** Additional notes regarding the quarantine (optional).

## Implementation
1. Utilize a `DateField` for precise recording of the quarantine start date.
2. Track the cow associated with each quarantine record.
3. Provide predefined choices for quarantine reasons.
4. Allow for recording the end date of the quarantine (if applicable).
5. Allow for optional notes to be recorded.

## Validation
Validation checks are implemented before saving the quarantine record to ensure data integrity.
- Implement validation for the reason for quarantine.
- Validate the date range for the start and end dates.
- Ensure that a single cow cannot have overlapping quarantine records.

## Discussion Points
- Define the attributes in the `QuarantineRecord` model.
- Discuss any potential integration with other relevant models.
- Describe the validation checks implemented before saving the record.
- Consider any additional features or modifications needed for the `QuarantineRecord` model.

Feel free to provide your insights and suggestions on the proposed `QuarantineRecord` model implementation.

```python
class QuarantineRecord(models.Model):
    class Meta:
        get_latest_by = "-start_date"

    cow = models.ForeignKey(
        Cow, on_delete=models.CASCADE, related_name="quarantine_record"
    )
    reason = models.CharField(max_length=35, choices=QuarantineReasonChoices.choices)
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(null=True)
    notes = models.TextField(null=True, max_length=100)

    def __str__(self):
        if self.end_date:
            return f"Quarantine Record of {self.cow.tag_number} from {self.start_date} to {self.end_date}"
        return f"Quarantine Record of {self.cow.tag_number} from {self.start_date}"

    def clean(self):
        QuarantineValidator.validate_reason(self.reason, self.cow)
        QuarantineValidator.validate_date(self.start_date, self.end_date, self.pk)

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)
```
Your input on this matter is highly valued for the successful integration of the `QuarantineRecord` model into the Dairy Django Backend. Let's discuss and refine this proposal further.

**Comment by mamesareagan** [comment]
with this model,,I was thinking the cows that are almost calving can also be moved to quarantine .What are the thougts on this?

**Comment by peter-evance** [comment]
> with this model,,I was thinking the cows that are almost calving can also be moved to quarantine .What are the thougts on this?
> 

Interesting idea.

That's quite logical.
