### ISSUE TITLE
Implement Insemination Model

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#22]
### Background
In the ongoing development of the Dairy Django Backend, the introduction of an `Insemination` model is crucial to accurately record and manage cow insemination information.

### Insemination Model Requirements
- **date_of_insemination (DateTime):** The date and time of the insemination.
- **cow (Cow):** The cow that underwent the insemination.
- **pregnancy (Pregnancy or None):** The associated pregnancy record, if insemination is successful.
- **success (Boolean):** Indicates whether the insemination was successful or not.
- **notes (String):** Additional notes related to the insemination.
- **inseminator (Inseminator):** The inseminator responsible for the procedure.
- **semen (Semen or None):** The type of semen used for the insemination.

### Note
The term "insemination" refers to the process of introducing semen into the reproductive tract of a female animal.

## Implementation
1. Utilize `DateTimeField` for precise recording of the insemination date and time.
2. Track the cow associated with each insemination record.
3. Provide an option for an associated pregnancy record.
4. Use a boolean field to indicate the success of the insemination.
5. Allow for additional notes related to the insemination.
6. Associate an inseminator and specify the type of semen used.

## Validation
Validation checks are implemented before saving the insemination record to ensure data integrity.
- Validate that the insemination is not within 21 days of the previous insemination.
- Ensure that the cow is not already in heat during the insemination.

## Discussion Points
- Define the attributes in the `Insemination` model.
- Discuss any potential integration with other relevant models.
- Describe the validation checks implemented before saving the record.
- Consider any additional features or modifications needed for the `Insemination` model.

Feel free to provide your insights and suggestions on the proposed `Insemination` model implementation.

```python
class Insemination(models.Model):
    """
    Represents a record of cow insemination.

    Attributes:
    - `date_of_insemination` (datetime): The date and time of the insemination.
    - `cow` (Cow): The cow that underwent the insemination.
    - `pregnancy` (Pregnancy or None): The associated pregnancy record, if insemination is successful.
    - `success` (bool): Indicates whether the insemination was successful or not.
    - `notes` (str): Additional notes related to the insemination.
    - `inseminator` (Inseminator): The inseminator responsible for the procedure.
    - `semen` (Semen or None): The type of semen used for the insemination.

    Note: The term "insemination" refers to the process of introducing semen into the reproductive tract of a female animal.
    """

    date_of_insemination = models.DateTimeField(auto_now_add=True)
    cow = models.ForeignKey(Cow, on_delete=models.PROTECT, related_name="inseminations")
    pregnancy = models.OneToOneField(
        Pregnancy, on_delete=models.PROTECT, editable=False, blank=True, null=True
    )
    success = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    inseminator = models.ForeignKey(
        Inseminator, on_delete=models.PROTECT, related_name="inseminations_done"
    )
    semen = models.ForeignKey("Semen", on_delete=models.PROTECT, blank=True, null=True)

    objects = models.Manager()
    manager = InseminationManager()

    @property
    def days_since_insemination(self):
        """
        Returns: Days since the cow was last inseminated
        """
        return InseminationManager.days_since_insemination(self)

    def __str__(self):
        return f"Insemination record for cow {self.cow.tag_number} on {self.date_of_insemination}"

    def clean(self):
        """
        Performs validation checks before saving the insemination record.

        Raises:
        - `ValidationError`: If insemination record validation fails.
        """
        InseminationValidator.validate_within_21_days_of_previous_insemination(
            self.pk, self.cow
        )

    def save(self, *args, **kwargs):
        """
        Overrides the save method to ensure validation before saving.
        """
        self.clean()
        super().save(*args, **kwargs)
        InseminationValidator.validate_already_in_heat(
            self.cow, self.date_of_insemination
        )
```
Your input on this matter is highly valued for the successful integration of the `Insemination` model into the Dairy Django Backend. Let's discuss and refine this proposal further

**Comment by steve2700** [comment]
is this issue still available ,  in which app can we put this model

**Comment by peter-evance** [comment]
> is this issue still available , in which app can we put this model

It's tentatively closed, I'm yet to push the code that I have worked on. Nevertheless you can work on it and push your idea too, we shall discuss on how to integrate them

**Comment by steve2700** [comment]
you can push Peter the idea you clearly showed there that was my idea too

**Comment by steve2700** [comment]
you can also open some issues too , i want to contribute

**Comment by peter-evance** [comment]
> you can also open some issues too , i want to contribute

Ok.
