### ISSUE TITLE
Issue: Permissions and Roles for CustomUser Model

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#3]
### Description

**Background:**
As we continue to develop the Dairy Django Backend, establishing a robust system for permissions and roles is vital. The CustomUser model includes additional fields such as `is_farm_owner`, `is_farm_manager`, `is_assistant_farm_manager`, `is_team_leader`, and `is_farm_worker` to define user roles.

### Permission Requirements

1. Define specific permissions for each role.
2. Discuss how these permissions will be applied in different parts of the application.
3. Integrate permissions with the existing authentication strategy.

### Proposed Solution

I propose creating a `permissions.py` file to house permission classes like `IsFarmOwner`, which can be utilized in viewsets and APIViews through the `permission_classes` attribute. These classes will enable condition checks such as `if request.user.is_farm_owner`.

### Discussion Points

1. Define permission classes corresponding to each role.
2. Discuss how these classes will be integrated into viewsets and APIViews.
3. Consider any additional permissions or modifications needed.

### Implementation

- Provide code snippets for the proposed permission classes.
- Detail how these classes will be applied in viewsets/APIViews.

### Next Steps

1. **Review and Feedback:**
   - Seek feedback on the proposed solution and its implementation.
   - Ensure alignment with the overall project goals.

2. **Decision Making:**
   - Finalize the set of permissions for each role.
   - Confirm integration with the existing authentication and token strategy.

3. **Documentation:**
   - Update project documentation to include information about the implemented permissions.

### Additional Information

- [Link to Django Permissions Documentation](https://docs.djangoproject.com/en/5.0/topics/auth/default/#permissions)
- [Link to Django Rest Framework Permissions](https://www.django-rest-framework.org/api-guide/permissions/)
- Any other relevant documentation or articles.

Let's collaborate on this issue to establish a clear and effective system for managing permissions and roles within our Dairy Django Backend.

**Comment by mamesareagan** [comment]
I had this idea to have the classes representing each role and having a method to check if the user satisfies  the conditions of a certain role. This will be checked in the views from the permision classes  attribute as mentioned

**Comment by peter-evance** [comment]
> I had this idea to have the classes representing each role and having a method to check if the user satisfies the conditions of a certain role. This will be checked in the views from the permision classes attribute as mentioned

Sure, that has a striking similarity to what I am thinking as at now of eg:

```
from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import BasePermission

class IsFarmManager(BasePermission):
    """
    Custom permission class that allows only farm owners and managers to perform an action.

    Raises:
    - `PermissionDenied`: If the user is not a farm owner or a farm manager.

    Usage:
        Add the permission class to the view or viewset that requires farm owners and managers access:
        permission_classes = [IsFarmManager]
    """

    message = {
        "detail": "Only farm owners and managers have permission to perform this action."
    }

    def has_permission(self, request, view):
        # Check if the current user is a farm manager
        if request.user.is_authenticated and (
            request.user.is_farm_manager or request.user.is_farm_owner
        ):
            return True
        raise PermissionDenied(self.message)

```

**Comment by mamesareagan** [comment]
Another thing,what should be the urls for the users and their roles.I say that assuming we will have views for each role .
