### ISSUE TITLE
Introduce Pathogen Model

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#34]
## Description

In the evolving development of the Django Dairy Backend, the introduction of a Pathogen model is essential to manage and document information related to pathogens affecting cow health.

**Pathogen Model Requirements:**

**Fields:**
- `name` (str): The name of the pathogen.

**Validation:**
- Implement validation checks to ensure the integrity of pathogen names.

**Methods:**
- Implement a `clean` method for data validation.
- Explore the potential for additional methods based on project requirements.

**Documentation:**
- Update project documentation to include details about the Pathogen model.

**Comment by steve2700** [comment]
class Pathogen(models.Model):
    """
    Represents a pathogen affecting cow health.

    Attributes:
    - `name` (str): The name of the pathogen.
    - `species` (str): The species of the pathogen (e.g., virus, bacteria).
    - `transmission_routes` (ManyToManyField): Transmission routes of the pathogen.
    - `symptoms` (TextField): Symptoms associated with the pathogen.
    - `treatment_options` (TextField): Treatment options for the pathogen.

    Methods:
    - `__str__`: Returns a string representation of the pathogen.
    - `clean`: Performs validation checks before saving the pathogen.

    Additional Methods:
    - `count_infected_cows`: Returns the number of cows infected with this pathogen.
    - `is_transmissible_to_humans`: Indicates if the pathogen can infect humans.
    - `get_treatment_guidelines`: Provides links or summaries of recommended treatment protocols.
    """

    name = models.CharField(max_length=255, unique=True)
    species = models.CharField(max_length=100, blank=True, null=True)
    transmission_routes = models.ManyToManyField('TransmissionRoute', blank=True)
    symptoms = models.TextField(blank=True, null=True)
    treatment_options = models.TextField(blank=True, null=True)

    def __str__(self):
        """
        Returns a string representation of the pathogen.
        """
        return self.name

    def clean(self):
        """
        Performs validation checks before saving the pathogen.

        Raises:
        - `ValidationError`: If validation fails.
        """
        # Example: Trim leading and trailing spaces, convert to uppercase.
        self.name = self.name.strip().upper()

        # Add additional validation checks for other fields.
        # Example: Check if the name is alphanumeric.
        # if not self.name.isalnum():
        #     raise ValidationError("Pathogen name must be alphanumeric.")

    def count_infected_cows(self):
        """
        Returns the number of cows infected with this pathogen.
        """
        # Customize implementation logic for counting infected cows.
        # For example: return Cow.objects.filter(infected_pathogens=self).count()

    def is_transmissible_to_humans(self):
        """
        Indicates if the pathogen can infect humans.
        """
        # Customize implementation logic for checking transmissibility.
        # For example: return self.transmission_routes.filter(target="Humans").exists()

    def get_treatment_guidelines(self):
        """
        Provides links or summaries of recommended treatment protocols.
        """
        # Customize implementation logic for retrieving treatment guidelines.
        # For example: return TreatmentGuideline.objects.filter(pathogen=self)

class TransmissionRoute(models.Model):
    """
    Represents a transmission route of a pathogen.

    Attributes:
    - `name` (str): The name of the transmission route.

    Methods:
    - `__str__`: Returns a string representation of the transmission route.
    """

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """
        Returns a string representation of the transmission route.
        """
        return self.name
