### ISSUE TITLE
Proposed Concept: Introduce Disease Model

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#35]
## Description:
In the conceptualization phase of the Django Dairy Backend development, a proposed concept for a Disease model is introduced. This model aims to effectively manage and record information related to diseases affecting cows.

**Disease Model Concept:**

**Fields:**
- `name` (str, unique): The name of the disease.
- `pathogen` (ForeignKey to Pathogen): The pathogen associated with the disease.
- `category` (ForeignKey to DiseaseCategory): The category to which the disease belongs.
- `date_reported` (Date, auto_now_add=True): The date when the disease is reported.
- `is_recovered` (BooleanField, default=False): Indicates whether the disease is recovered.
- `recovered_date` (Date, editable=False, blank=True, null=True): The date when the disease is marked as recovered.
- `notes` (TextField, blank=True): Additional notes related to the disease.

**Relationships:**
- `cows` (ManyToManyField to Cow, related_name="diseases"): The cows affected by the disease.
- `symptoms` (ManyToManyField to Symptoms, related_name="diseases"): The symptoms associated with the disease.
- `treatments` (ManyToManyField to Treatment, related_name="diseases"): The treatments applied for the disease.

**Validation:**
- Ensure that if a disease is marked as recovered, a recovered date is required.
- Ensure that if a recovered date is provided, the disease must be marked as recovered.
- Validate that the recovered date is after the occurrence date.
- Ensure that the occurrence date is not in the future.
- Validate the presence of the disease name and associated pathogen.
- Ensure that if a disease is recovered, at least one treatment is required.

**Discussion Points:**

**Data Integrity:**
- Emphasize the importance of validation checks for maintaining data accuracy.
- Discuss any challenges or considerations related to data validation.

**Feedback:**
- Encourage team members to provide feedback on the proposed Disease model concept.

**Next Steps:**
1. Review the proposed Disease model concept and provide feedback.
2. Discuss any additional features or modifications needed.
3. Collaborate on refining and finalizing the Disease model.

---

**Note:**
This is a conceptual proposal, and feedback from the team is crucial for shaping the final implementation of the Disease model in the Django Dairy Project.

**Comment by NathanielWatife** [comment]
@peter-evance May i try my best to do something here?
Whatever questions i have i will let you know.
And am i allowed to use resources like google or open AI for more explanations?

**Comment by peter-evance** [comment]
> @peter-evance May i try my best to do something here? Whatever questions i have i will let you know. And am i allowed to use resources like google or open AI for more explanations?

Sure you are open to give that a try!

**Comment by NathanielWatife** [comment]
Okay boss I will do my best
