### ISSUE TITLE
Issue: Introduce Milk Inventory Model Concept

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#59]
***Description:***
In the ongoing development of the Django Dairy Backend, we propose the introduction of a Milk Inventory Model. This model is intended to manage and record information related to milk inventory, providing a structured approach to track milk production, storage, and usage.

---

**Milk Inventory Model Concept:**

**Fields:**
- `cow` (ForeignKey to Cow): The cow from which the milk is obtained.
- `date_of_production` (DateTime, auto_now_add=True): The date and time when the milk is produced.
- `quantity` (DecimalField): The quantity of milk produced.
- `storage_location` (CharField): The location where the milk is stored.
- `usage` (CharField): The purpose for which the milk is used (e.g., sale, processing).

**Validation:**
- Ensure that the quantity of milk is a positive number.
- Validate the presence of a storage location.
- Validate the presence of usage information.

**Discussion Points:**

**Data Integrity:**
- Emphasize the importance of validation checks for maintaining accurate milk inventory data.
- Discuss any challenges or considerations related to data validation.

**Feedback:**
- Encourage team members to provide feedback on the proposed Milk Inventory Model concept.

---

**Next Steps:**
1. Review the proposed Milk Inventory Model concept and provide feedback.
2. Discuss any additional features or modifications needed.
3. Collaborate on refining and finalizing the Milk Inventory Model.

**Note:**
This is a conceptual proposal, and feedback from the team is crucial for shaping the final implementation of the Milk Inventory Model in the Django Dairy Project.

---

Your input and suggestions for further refinement are highly appreciated.

---

@peter-evance

**Comment by mamesareagan** [comment]
With this model, is there a need to validate the cows gender and age?
My perception is this cow will already be validated in the milk  production Model.

**Comment by peter-evance** [comment]
> With this model, is there a need to validate the cows gender and age?
> My perception is this cow will already be validated in the milk  production Model.

This should be automatically populated, thus no need for validations.
