### ISSUE TITLE
Issue: CowBreed Model and Validation Strategy

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#6]
### Description

**Background:**
As we move forward with the development of the Dairy Django Backend, it's essential to establish a robust data model for cow breeds. In Kenya, we have several distinct breeds, including Friesian, Sahiwal, Jersey, Guernsey, Crossbreed, and Ayrshire. To maintain data consistency and accuracy, we need to implement a validation strategy for the cow breed names.

### Validation Requirements

Define a validation strategy for the `CowBreed` model to ensure that only valid breed names are accepted. If the provided breed name is not among the specified choices, the server should throw an error.

### Proposed Solution

I propose implementing a `TextChoices` enumeration for the `CowBreed` model's field that represents the breed name. This will leverage Django's `TextChoices` class to define a set of valid choices for the breed name field.

### Discussion Points

1. Define the field in the `CowBreed` model representing the breed name.
2. Specify the `TextChoices` enumeration with the list of valid breed names.
3. Discuss how the validation error should be handled on the server side.

**Comment by mamesareagan** [comment]
we have two classes, one class to hold the choices of cow breeds and the other one can check the breed name against the available choices.

**Comment by peter-evance** [comment]
> we have two classes, one class to hold the choices of cow breeds and the other one can check the breed name against the available choices.
> 

Sure, one for choices enumeration and another class/function to be called during model's save to perform validation checks.
