### ISSUE TITLE
 Issue: Cow Model Creation with Field Definitions and Validation Checks

### ISSUE THREAD

**Issue by peter-evance** [AgriCodeHub/dairy-django-backend#7]
### Description

**Background:**
As part of the Dairy Django Backend development, we need to create a comprehensive `Cow` model that includes various fields to capture essential information about each cow. Additionally, we aim to implement validation checks to ensure data integrity and consistency.

### Cow Model Requirements

1. **Breed:**
   - Field to capture the breed of the cow.

2. **Automatic Tag Number Generation:**
   - Implement an automatic generation of a unique tag number for each cow.

3. **Parity:**
   - Field to track the parity of the cow.

4. **Age:**
   - Field to capture the age of the cow.

5. **Age in Farm:**
   - Field to calculate and store the age of the cow since introduction to the farm.

6. **Name:**
   - Field for the name of the cow.

7. **Date of Birth:**
   - Field to store the date of birth of the cow.

8. **Gender:**
   - Field to specify the gender of the cow.

9. **Availability Status:**
   - Field to indicate the availability status of the cow.

10. **Current Pregnancy Status:**
   - Field to track the current pregnancy status of the cow.

11. **Category:**
    - Field to categorize the cow (e.g., calf, heifer, milking cow).

12. **Current Production Status:**
    - Field to capture the current production status of the cow.

13. **Date Introduced in Farm:**
    - Field to record the date the cow was introduced to the farm.

14. **Is Bought:**
    - Field to indicate whether the cow was bought.

15. **Date of Death:**
    - Field to capture the date of death if applicable.

16. **Sire:**
    - Field to specify the sire of the cow.

17. **Dam:**
    - Field to specify the dam of the cow.

### Validation Checks

- If a cow is categorized as a calf, the production status should be limited to calf-related statuses.
- Implement additional validation checks as needed for data consistency.

**Comment by mamesareagan** [comment]
*DEALERS IN SYSTEM ADMINISTRATION AND WEBSITE DESIGN*
